name: Run automated tests

on:
  pull_request:
    branches:
      - main

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out source code
      - name: Checkout project sources
        uses: actions/checkout@v4

      # Step 2: Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 3: Run tests with Gradle
      - name: Run Test with Gradle Wrapper
        run: ./gradlew test
