name: GitHub Actions Demo
on: push # Trigger on any push/commit
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print the triggering event
        run: echo "The job was triggered by ${{ github.event_name }}."
      - name: Print the OS of the runner
        run: echo "This job is running on a ${{ runner.os }} server" 
      - name: Check out repository code action
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ github.workspace }}
