name: Run automated tests
on: push
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the project's source code
      - name: Checkout project sources
        uses: actions/checkout@v4 
      # Step 2: Set up the Gradle build tool
      - name: Setup Gradle 
        uses: gradle/gradle-build-action@v2
      # Step 3: Run tests using the Gradle Wrapper
      - name: Run Test with Gradle Wrapper
        run: ./gradlew test
